services:
    web:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            DEBUG: 1
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        env_file:
            - .env
        environment:
            POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=uk-UA-x-icu --encoding=UTF8
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data: